name: user_environment
version: 1.0.1
description: 'User environment detection'
homepage: http://www.github.com/wrike/user-environment.dart
authors:
- Oleg Bezuglov <oleg.bezuglov@team.wrike.com>

environment:
  sdk: '>=1.24.1 <2.0.0'

dependencies:
  browser_detect: ^1.0.4
  js: ^0.6.1

dev_dependencies:
  analyzer: ^0.29.2
  mockito: ^2.0.0
  test: ^0.12.24+1
  dart_dev: any
  dart_style: any

transformers:
- test/pub_serve:
    $include: test/**_test{.*,}.dart
